---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bh-admission-config
  namespace: bh-admission
data:
  bh-admission.properties: |
    external_api_url=https://localhost:8080
    external_api_timeout=10
    requester_key=mycompany.com/requester
    listen_addr=0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  name: bh-admission
  namespace: bh-admission
  labels:
    name: bh-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: bh-admission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bh-admission
  namespace: bh-admission
  labels:
    name: bh-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bh-admission
  template:
    metadata:
      name: bh-admission 
      labels:
        name: bh-admission
    spec:
      containers:
        - name: webhook
#          image: image-registry.openshift-image-registry.svc:5000/openshift/bh-admission:latest
#          image: docker-registry.default.svc:5000/openshift/bh-admission:latest
          image: localhost:5000/bh-admission:latest
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: "true"
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 50Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: bh-admission-config
              mountPath: /etc/webhook/bh-admission-config
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: bh-admission-certs
        - name: bh-admission-config
          configMap:
            name: bh-admission-config
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: bh-admission
webhooks:
  - name: bh-admission.cust.local
    clientConfig:
      service:
        name: bh-admission
        namespace: bh-admission
        path: "/"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE"]
        apiGroups: ["", "project.openshift.io"]
        apiVersions: ["v1"]
        resources: ["namespaces","projects"]
      - operations: ["CREATE"]
        apiGroups: ["", "user.openshift.io"]
        apiVersions: ["v1"]
        resources: ["users","serviceaccounts"]
    failurePolicy: Ignore
